#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for controlling a FLI Colour Filter Wheel"""

import glob
import json
import os
import sys
import Pyro4
from rockit.common import TFmt
from rockit.cfw import Config, CommandStatus, CFWStatus


SCRIPT_NAME = os.path.basename(sys.argv[0])
sys.excepthook = Pyro4.util.excepthook


def run_command(command, args):
    """Runs a daemon command, handling error messages"""
    if 'CFWD_CONFIG_PATH' in os.environ:
        config = Config(os.environ['CFWD_CONFIG_PATH'])
    else:
        # Load the config file defined in the CFWD_CONFIG_PATH environment variable or from the
        # default system location (/etc/cfwd/). Exit with an error if zero or multiple are found.
        files = glob.glob("/etc/cfwd/*.json")
        if len(files) != 1:
            print('error: failed to guess the default config file. ' +
                  'Run as CFWD_CONFIG_PATH=/path/to/config.json cfw <command>')
            return 1

        config = Config(files[0])

    try:
        ret = command(config, args)
    except Pyro4.errors.CommunicationError:
        ret = -101

    # Print message associated with error codes, except for -1 (error handled locally)
    if ret not in [-1, 0]:
        print(CommandStatus.message(ret))
    sys.exit(ret)


def print_status(config, _):
    """Prints a human-readable summary of the filter wheel status"""
    with config.daemon.connect() as cfwd:
        data = cfwd.report_status()

    print(f'Filter Wheel is {CFWStatus.label(data[f"status"], True)}')
    if 'filter' in data:
        print(f'Filter is {TFmt.Bold}{data["filter"]}{TFmt.Clear}')
    return 0


def print_json(config, _):
    """Prints a machine-readable summary of the filter wheel status"""
    with config.daemon.connect() as cfwd:
        print(json.dumps(cfwd.report_status() or {}))

    return 0


def set_filter(config, args):
    """Select a filter"""
    if len(args) == 1 and (args[0] in config.filters):
        with config.daemon.connect(timeout=config.move_timeout + 5) as cfwd:
            return cfwd.set_filter(args[0])
    print(f'usage: {SCRIPT_NAME} set ({"|".join(config.filters)})')
    return -1


def initialize(config, _):
    """Connect to the filter wheel"""
    with config.daemon.connect(timeout=config.move_timeout + 5) as cfwd:
        return cfwd.initialize()


def shutdown(config, *_):
    """Disconnect from the filter wheel"""
    with config.daemon.connect() as cfwd:
        return cfwd.shutdown()


def print_filters(config, *_):
    """Prints a list of selectable filters"""
    print(' '.join(config.filters))
    return 0


def print_usage():
    """Prints the utility help"""
    print(f'usage: {SCRIPT_NAME} <command> [<args>]')
    print()
    print('general commands:')
    print('   set          change filter')
    print('   status       print a human-readable summary of the filter wheel status')
    print('   json         print a machine-readable summary of the filter wheel status')
    print('engineering commands:')
    print('   init         connect to the filter wheel')
    print('   kill         disconnect from the filter wheel')
    print()

    return 0


if __name__ == '__main__':
    commands = {
        'set': set_filter,
        'status': print_status,
        'json': print_json,
        'init': initialize,
        'kill': shutdown,
        'list-filters': print_filters
    }

    if len(sys.argv) >= 2 and sys.argv[1] in commands:
        sys.exit(run_command(commands[sys.argv[1]], sys.argv[2:]))

    sys.exit(print_usage())
